# Generated by Django 4.1.1 on 2022-09-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parenttweet', to='tweet.tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweetid', to='tweet.tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='sub_parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subparenttweet', to='tweet.tweet'),
        ),
    ]
